# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from signup import Ui_Dialog
from won import Ui_Dialog_won
from viewer import QImageViewer

import pymysql

class Ui_DialogLogin(object):
    def setupUi(self, DialogLogin):
        DialogLogin.setObjectName("DialogLogin")
        DialogLogin.resize(658, 558)
        self.label_Heading = QtWidgets.QLabel(DialogLogin)
        self.label_Heading.setGeometry(QtCore.QRect(260, 100, 150, 42))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label_Heading.setFont(font)
        self.label_Heading.setObjectName("label_Heading")
        self.label = QtWidgets.QLabel(DialogLogin)
        self.label.setGeometry(QtCore.QRect(120, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogLogin)
        self.label_2.setGeometry(QtCore.QRect(100, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnLogin = QtWidgets.QPushButton(DialogLogin)
        self.btnLogin.setGeometry(QtCore.QRect(260, 340, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.btnLogin.setFont(font)
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.clicked.connect(self.Login)
        self.btnSignup = QtWidgets.QPushButton(DialogLogin)
        self.btnSignup.setGeometry(QtCore.QRect(260, 400, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.btnSignup.setFont(font)
        self.btnSignup.setObjectName("btnSignup")
        self.btnSignup.clicked.connect(self.signupButton)
        self.textID = QtWidgets.QLineEdit(DialogLogin)
        self.textID.setGeometry(QtCore.QRect(250, 170, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.textID.setFont(font)
        self.textID.setObjectName("textID")
        self.textPassword = QtWidgets.QLineEdit(DialogLogin)
        self.textPassword.setGeometry(QtCore.QRect(250, 230, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.textPassword.setFont(font)
        self.textPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textPassword.setObjectName("textPassword")

        self.retranslateUi(DialogLogin)
        QtCore.QMetaObject.connectSlotsByName(DialogLogin)

    def login2(self, id, password):
        self.db = pymysql.connect(host='localhost' , user='root' , password ='shrkfl21' , db='USER_')
        self.cursor = self.db.cursor()
        self.cursor.execute("SELECT * FROM user WHERE ID = %s AND PASSWORD = %s", (id, password))
        data = self.cursor.fetchall()
        for row in data:
         if id == row[0] and password == row[0]:
            print(" ")
            
            return True
         else:
            print(" ")
            return False

    def Login(self):
        self.db = pymysql.connect(host='localhost' , user='root' , password ='shrkfl21' , db='USER_')
        self.cur = self.db.cursor()
        id = self.textID.text()
        password = self.textPassword.text()
        getdb = Ui_DialogLogin()        
        result = getdb.login2(id,password)
       
        
        self.cur.execute("SELECT * FROM user WHERE NAME = %s AND PASSWORD = %s", (id, password))

        
        
        if self.checkFields(id,password):
            self.showMessage(" ", "빈칸을 채워주세요")
        else:
            
         
            if result == None:
                self.showMessage(" ", "아이디와 비밀번호를 확인해주세요")
            else:

                self.showMessage(" ", "로그인성공")
                self.QimageViewer()
                
                
                
    def retranslateUi(self, DialogLogin):
        _translate = QtCore.QCoreApplication.translate
        DialogLogin.setWindowTitle(_translate("DialogLogin", "20조 종합설계-로그인 화면"))
        self.label_Heading.setText(_translate("DialogLogin", "Dicom Viewer"))
        self.label.setText(_translate("DialogLogin", "ID"))
        self.label_2.setText(_translate("DialogLogin", "Password"))
        self.btnLogin.setText(_translate("DialogLogin", "LogIn"))
        self.btnSignup.setText(_translate("DialogLogin", "Sign In"))

    def won(self):
        self.wonDialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog_won()
        self.ui.setupUi(self.wonDialog)
        self.wonDialog.show()


    def QimageViewer(self):
        self.app = QApplication(sys.argv)
        self.imageViewer = QImageViewer()
        self.imageViewer.show()


    def showMessage(self,title,msg):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        #msgBox.setTitle(title)
        msgBox.setText(msg)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()
   
    def signupButton(self):   
        self.signDialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.signDialog)
        self.signDialog.show()


    def clearField(self):
        self.textID.setText(None)
        self.textPassword.setText(None)
    def checkFields(self,id,password):
        if(id=="" or password== ""):
            return True

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogLogin = QtWidgets.QDialog()
    ui = Ui_DialogLogin()
    ui.setupUi(DialogLogin)
    DialogLogin.show()

    sys.exit(app.exec_())
