# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(636, 577)
        self.label_Heading = QtWidgets.QLabel(Dialog)
        self.label_Heading.setGeometry(QtCore.QRect(230, 40, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.label_Heading.setFont(font)
        self.label_Heading.setObjectName("label_Heading")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 140, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 210, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 280, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 350, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnRegister = QtWidgets.QPushButton(Dialog)
        self.btnRegister.setGeometry(QtCore.QRect(230, 440, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.btnRegister.setFont(font)
        self.btnRegister.setObjectName("btnRegister")
        self.btnRegister.clicked.connect(self.registerButton)
        self.textID = QtWidgets.QLineEdit(Dialog)
        self.textID.setGeometry(QtCore.QRect(250, 140, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.textID.setFont(font)
        self.textID.setObjectName("textID")
        self.textNAME = QtWidgets.QLineEdit(Dialog)
        self.textNAME.setGeometry(QtCore.QRect(250, 210, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.textNAME.setFont(font)
        self.textNAME.setObjectName("textNAME")
        self.textPassword = QtWidgets.QLineEdit(Dialog)
        self.textPassword.setGeometry(QtCore.QRect(250, 280, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.textPassword.setFont(font)
        self.textPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textPassword.setObjectName("textPassword")
        self.textPassword2 = QtWidgets.QLineEdit(Dialog)
        self.textPassword2.setGeometry(QtCore.QRect(250, 350, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.textPassword2.setFont(font)
        self.textPassword2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.textPassword2.setObjectName("textPassword2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def signup(self,id, name, password):
        self.db = pymysql.connect(host='localhost' , user='root' , password ='shrkfl21' , db='USER_')
        self.cur = self.db.cursor()
        
        
        
    def registerButton(self):
        self.db = pymysql.connect(host='localhost' , user='root' , password ='shrkfl21' , db='USER_')
        self.cur = self.db.cursor()

        id = self.textID.text()
        name = self.textNAME.text()
        password = self.textPassword.text()
        password2 = self.textPassword2.text()
        if self.checkFields(id,name,password):
            self.showMessage(" ", "빈칸을 채워주세요")
        else:
         if password == password2:
            self.cur.execute("INSERT INTO user VALUES('%s','%s','%s')" % (id, name,password))

            self.db.commit()
            self.showMessage(" ","회원가입 성공")
         else:
            self.showMessage(" ", "비밀번호를 확인해주세요")
            
    def showMessage(self,title,msg):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Information)

        msgBox.setText(msg)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "20조 종합설계-회원가입 화면"))
        self.label_Heading.setText(_translate("Dialog", "회원가입"))
        self.label.setText(_translate("Dialog", "아이디"))
        self.label_2.setText(_translate("Dialog", "이름"))
        self.label_3.setText(_translate("Dialog", "비밀번호"))
        self.label_4.setText(_translate("Dialog", "비밀번호 확인"))
        self.btnRegister.setText(_translate("Dialog", "회원가입"))

    def loginPage(self):
        self.loginWindow = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.loginWindow)
        self.loginWindow.show()
        
    def checkFields(self,ID,name,password):
        if(id == "" or name == "" or password== ""):
            return True
        


    def checkPassword(self,password1, password2):
        return password1 == password2


    def clearField(self):
        self.textID.setText(None)
        self.textNAME.setText(None)
        self.textPassword.setText(None)
        self.txtPassword2.setText(None)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
